const fs = require('fs');
const path = require('path');

// Look for .env in frontend folder first, then repo root
const candidates = [
  path.join(__dirname, '..', '.env'),
  path.join(__dirname, '..', '..', '.env')
];

let envPath = null;
for (const p of candidates) {
  if (fs.existsSync(p)) {
    envPath = p;
    break;
  }
}

const defaultEnv = { API_URL: 'http://localhost:3000' };
let vars = { ...defaultEnv };

if (envPath) {
  const content = fs.readFileSync(envPath, 'utf8');
  content.split(/\r?\n/).forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const idx = trimmed.indexOf('=');
    if (idx === -1) return;
    const key = trimmed.substring(0, idx).trim();
    let val = trimmed.substring(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.substring(1, val.length - 1);
    }
    vars[key] = val;
  });
} else {
  console.log('.env not found, using default API_URL');
}

if (process.env.API_URL) {
  vars.API_URL = process.env.API_URL;
}

if (vars.API_URL && !/^https?:\/\//i.test(vars.API_URL)) {
  vars.API_URL = `https://${vars.API_URL}`;
}

const outPath = path.join(__dirname, '..', 'public', 'env.js');
const content = `// Generated by scripts/generate-env.js\n(function (window) {\n  window.__env = window.__env || {};\n  window.__env.API_URL = '${vars.API_URL.replace(/'/g, "\\'")}';\n}(this));\n`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Generated', outPath);
